# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uZNLDdTPSSDFNVhNuao8GMysLzaKLDo
"""

import pandas as pd

teacher = pd.DataFrame({
     'FISH': ['Qadamova Zulayho ','Ibragimov.N','Karimov.S','Torayeva M'],
      'Fani':[ 'Suniy asoslari','Mikroiqtisodiyot','Suniy intelekt asoslari','Sotib olish tamoyillari'],
      'Mashgulot turi': ['amaliy','maruza','maruza','amaliy'],
        "Kafedrasi": ['Axborout tehnalogiyalarri', 'Axborout tehnalogiyalari','Axborout tehnalogiyalari','Axborout tehnalogiyalari'],

})

print(teacher)

teacher.to_excel('najmiddin_pro_max.xlsx')